# snakemake --cores 4

pipeline:
  name: "rnaseq"
  version: "1.0.0"
  organism: "droso"
  genome_build: "dr6"

paths:
  data_dir: "data"
  reference_dir: "reference"
  results_dir: "results"
  adapters: "reference/adapters.fa"

samples: "config/samples.tsv"

library:
  paired_end: true
  strandedness: "reverse"   # unstranded|forward|reverse

reference:
  genome: "reference/genome.fa"
  annotation: "reference/annotation.gtf"

trimming:
  enable: true
  tool: "trimmomatic"
  adapters: "reference/adapters.fa"
  params: >
    ILLUMINACLIP:{adapters}:2:30:10
    LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

alignment:
  aligner: "star"
  two_pass: false
  read_files_command: "zcat"
  star_params: >
    --outSAMtype BAM Unsorted
    --outFilterType BySJout
    --outFilterMultimapNmax 20
    --alignSJoverhangMin 8
    --alignSJDBoverhangMin 1
    --outFilterMismatchNoverLmax 0.06
    --alignIntronMin 20
    --alignIntronMax 1000000
    --alignMatesGapMax 1000000

quantification:
  tool: "featurecounts"
  strandedness_map:
    unstranded: "0"
    forward: "1"
    reverse: "2"
  featurecounts_params: "-g gene_id -t exon -Q 10 -B -C"
  paired_end: true

differential_expression:
  design: "~ batch + condition"
  contrasts:
    - ["condition", "treated", "control"]
  alpha: 0.05
  lfc_threshold: 1.0
  shrinkage: "apeglm"

resources:
  star_index_threads: 8
  star_align_threads: 8
  trim_threads: 4
  sort_threads: 4
  featurecounts_threads: 4
  star_align_mem_gb: 32
  sort_mem_gb: 16

